name: Build FFTW3-MPI Conda Package MacOS

on: [ push ]

jobs:
  build_and_upload:
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Conda Build
        run: |
          conda install conda-build
          conda install anaconda
      - name: Build conda
        run: |
          cd conda/
          conda build -c conda-forge .
      - name: Publish to Conda MacOS
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/local/miniconda/conda-bld/osx-64/fftw3*.tar.bz2 --force
  install_and_test:
    needs: build_and_upload
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Package
        shell: bash -l {0}
        run: |
          conda activate base
          conda config --append channels conda-forge
          conda install -c i4ds fftw3